language: objective-c
os: osx
osx_image: xcode7.3

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

script:
    - set -o pipefail
    - xcodebuild -workspace profilesApp.xcworkspace -scheme profilesApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
    - xcodebuild test -workspace profilesApp.xcworkspace -scheme profilesApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty