language: objective-c
os: osx
osx_image: xcode7.3

script:
    - xctool -workspace profilesApp.xcworkspace -scheme profilesApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -workspace profilesApp.xcworkspace -scheme profilesApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO